#! /bin/sh

# starting sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

# setting color schemes
#xrdb merge ~/.Xresources &

# set the cursor as left pointer instead of the default 'x'
xsetroot -cursor_name left_ptr &

# starting picom
picom &

# setting wallpaper and extracting colors
WALL=$HOME/walls/catppuccin1.png

feh --bg-fill $WALL &

# starting polybar
~/.config/polybar/launch.sh &

# starting flameshot
flameshot &
# defining workspaces
bspc monitor -d 1 2 3 4 5 6 7 8

bspc config focus_follows_pointer true

bspc config top_padding 5

#bspc rule -a Firefox-esr desktop=1 follow=on

bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"
bspc config border_width 2
bspc config borderless_monocle true

bspc config gapless_monocle true
bspc config window_gap 12
bspc config split_ratio 0.52
